package de.henningwobken.vpex.main.controllers

enum class ExpectedClass {
    TAGMARK, ANYTAG, ATTRIBUTE, AVALUE, ATTRIBUTENAMESPACE, COMMENT, ANYNAMESPACE, NONE, CDATATAG, CDATADATA, SEARCH_HIGHLIGHT, SEARCH_ALL_HIGHLIGHT, BETWEENATTRIBUTES, ANYDATA
}
